/*
 *
 * Menu constants
 *
 */

export const REQUEST_NAVIGATION_LIST = 'REQUEST_NAVIGATION_LIST';
export const GET_NAVIGATION_LIST = 'GET_NAVIGATION_LIST';
export const GET_NAVIGATION_LIST_ERROR = 'GET_NAVIGATION_LIST_ERROR';
export const SET_LOADING = 'SET_LOADING';
export const SET_CURRENT_VIEW_ID = 'SET_CURRENT_VIEW_ID';
export const SET_DEFAULT_PAGE = 'SET_DEFAULT_PAGE';
